import {
  bulletList,
  codeBlock,
  doc,
  heading,
  paragraph,
  rule,
  table,
  text,
  type AdfDoc,
} from "@/lib/adf";
import type { GherkinScenario, TicketDraft } from "@/lib/types";

function scenarioToGherkin(scenario: GherkinScenario): string {
  const lines = [`Scenario: ${scenario.title}`];
  for (const g of scenario.given) lines.push(`  Given ${g}`);
  for (const w of scenario.when) lines.push(`  When ${w}`);
  for (const t of scenario.then) lines.push(`  Then ${t}`);
  return lines.join("\n");
}

export function draftToMarkdown(draft: TicketDraft): string {
  const gherkinBlock =
    draft.gherkin.length === 0
      ? "_No Gherkin scenarios required for this ticket type._"
      : draft.gherkin.map(scenarioToGherkin).join("\n\n");

  const dorTable = [
    "| Criterion | Status | Notes |",
    "|---|---|---|",
    ...draft.definitionOfReady.map(
      (row) => `| ${row.criterion} | ${row.status} | ${row.notes || " "} |`,
    ),
  ].join("\n");

  return [
    `# ${draft.summary}`,
    "",
    `**Company:** ${draft.companyId}`,
    `**Intent:** ${draft.intent}`,
    draft.playbookId ? `**Playbook:** ${draft.playbookId}` : "",
    `**Confidence:** ${Math.round(draft.confidence * 100)}%`,
    `**Project:** ${draft.projectKey}`,
    `**Issue type:** ${draft.issueType}`,
    draft.epicKey || draft.epicName
      ? `**Epic:** ${draft.epicName || ""}${draft.epicKey ? ` (${draft.epicKey})` : ""}`
      : "**Epic:** _unmapped_",
    draft.labels.length ? `**Labels:** ${draft.labels.join(", ")}` : "",
    "",
    "## Product Overview",
    draft.productOverview,
    "",
    "## Description",
    draft.description,
    "",
    "## Technical Information",
    "_Outline for developers to complete:_",
    `- Approach: ${draft.technical.approach}`,
    `- Services / APIs: ${draft.technical.servicesApis}`,
    `- Data model: ${draft.technical.dataModel}`,
    `- Feature flags / config: ${draft.technical.featureFlags}`,
    `- Rollout / monitoring: ${draft.technical.rolloutMonitoring}`,
    `- Open questions: ${draft.technical.openQuestions}`,
    "",
    "## QA Acceptance Criteria (Gherkin)",
    "```gherkin",
    gherkinBlock,
    "```",
    "",
    "## Definition of Ready",
    dorTable,
  ]
    .filter((line) => line !== undefined)
    .join("\n");
}

export function draftToAdf(draft: TicketDraft): AdfDoc {
  const gherkinText =
    draft.gherkin.length === 0
      ? "No Gherkin scenarios required for this ticket type."
      : draft.gherkin.map(scenarioToGherkin).join("\n\n");

  return doc(
    heading(2, "Product Overview"),
    paragraph(text(draft.productOverview)),
    heading(2, "Description"),
    paragraph(text(draft.description)),
    heading(2, "Technical Information"),
    paragraph(text("Outline for developers to complete:")),
    bulletList([
      `Approach: ${draft.technical.approach}`,
      `Services / APIs: ${draft.technical.servicesApis}`,
      `Data model: ${draft.technical.dataModel}`,
      `Feature flags / config: ${draft.technical.featureFlags}`,
      `Rollout / monitoring: ${draft.technical.rolloutMonitoring}`,
      `Open questions: ${draft.technical.openQuestions}`,
    ]),
    heading(2, "QA Acceptance Criteria (Gherkin)"),
    codeBlock(gherkinText, "gherkin"),
    heading(2, "Definition of Ready"),
    table(
      ["Criterion", "Status", "Notes"],
      draft.definitionOfReady.map((row) => [
        row.criterion,
        row.status,
        row.notes || " ",
      ]),
    ),
    rule(),
    paragraph(
      text(
        "Generated by BA Jira Assistant — review before moving to Ready for Dev.",
        [{ type: "em" }],
      ),
    ),
  );
}
